name: Main

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm test
      - run: echo "$GITHUB_RUN_NUMBER" > test-artifact.txt
      - name: Download Base Artifact
        uses: ./
        with:
          artifact: "test-artifact.txt"
          path: base
      - uses: actions/upload-artifact@v2
        with:
          name: test-artifact.txt
          path: test-artifact.txt
