name: Main

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Base Artifact
        uses: ./
        with:
          artifact: "test-artifact.json"
